version: '3.3'

services:
      nginx:
        build:
            context: ../
            dockerfile: Dockerfile.nginx
        image: webhint/nginx:latest
        volumes:
            - certs:/etc/letsencrypt
            - certs-data:/data/letsencrypt
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            update_config:
                parallelism: 1
                delay: 30s
        ports:
            - 80:80
            - 443:443
volumes:
    certs:
    certs-data:
networks:
  default:
    external:
      # 'ingress' can't be use in the latest version of docker
      # and the default network created by docker breaks the
      # server. 'bridge' works, so for now we will use it.
      name: bridge
