version: '3.3'

services:
    config-manager:
        image: config-manager:latest
        build:
            context: ../
            dockerfile: Dockerfile.configmanager
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attemps: 3
            update_config:
                parallelism: 2
                delay: 10s
        environtment:
            - port=80
            - sessionSecret=<YourSessionSecret>
            - callbackURL=<YourCallbackUrl>
            - githubId=<YourGithubClientId>
            - githubSecret=<YourGithubSecret>
            - database=<YourDatabaseConnectionString>
        ports:
            - "3001:81"
    job-manager:
        image: job-manager:latest
        build:
            context: ../
            dockerfile: Dockerfile.jobmanager
        deploy:
            replicas: 4
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            update_config:
                parallelism: 2
                delay: 10s
        environment:
            - port=80
            - NODE_ENV=production
            - auth=<YourAuthCode>
            - queue=<YourAzureServiceBusConnectionString>
            - database=<YourDatabaseConnectionString>
        ports:
            - "3000:80"
    worker-service:
        image: worker-service:latest
        build:
            context: ../
            dockerfile: Dockerfile.worker
        deploy:
            replicas: 6
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            update_config:
                parallelism: 2
                delay: 10s
        environment:
            - CLOUDINARY_URL=<YourCloudinaryUrl>
            - queue=<YourAzureServiceBusConnectionString>
            - APP_INSIGHTS_KEY=<YourAppInsightKey>
    sync-service:
        image: sync-service:latest
        build:
            context: ../
            dockerfile: Dockerfile.sync
        deploy:
            replicas: 6
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            update_config:
                parallelism: 2
                delay: 10s
        environment:
            - queue=<YourAzureServiceBusConnectionString>
            - database=<YourDatabaseConnectionString>
            - APP_INSIGHTS_KEY=<YourAppInsightKey>
