version: '3.3'

services:
    job-manager:
        image: job-manager:latest
        build:
            context: ../
            dockerfile: Dockerfile.jobmanager
        deploy:
            replicas: 4
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            update_config:
                parallelism: 2
                delay: 10s
        environment:
            - port=80
            - NODE_ENV=production
            - auth=<YourAuthCode>
            - queue=<YourAzureServiceBusConnectionString>
            - database=<YourDatabaseConnectionString>
        ports:
            - "3000:80"
    worker-service:
        image: worker-service:latest
        build:
            context: ../
            dockerfile: Dockerfile.worker
        deploy:
            replicas: 6
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            update_config:
                parallelism: 2
                delay: 10s
        environment:
            - auth=<YourAuthCode>
            - queue=<YourAzureServiceBusConnectionString>
    sync-service:
        image: sync-service:latest
        build:
            context: ../
            dockerfile: Dockerfile.sync
        deploy:
            replicas: 6
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            update_config:
                parallelism: 2
                delay: 10s
        environment:
            - auth=<YourAuthCode>
            - queue=<YourAzureServiceBusConnectionString>
            - database=<YourDatabaseConnectionString>
